- !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - &id001 !!python/name:numpy.ndarray ''
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 128
  - &id002 !!python/object/apply:numpy.dtype
    args:
    - f8
    - 0
    - 1
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - false
  - !!binary |
    AAAAAPq8u78AAAAAuB22PwAAAKDF+ao/AAAAAOtRqb8AAACg74WxvwAAAECAhYm/AAAAIH6LtL8A
    AABA2m28vwAAAMBxCr8/AAAAQFscw78AAABAVyHKPwAAAECjx5o/AAAAwJlcxr8AAABAcyfCvwAA
    AEC9WZa/AAAA4Mveyj8AAACAfE/GvwAAAAA1G8W/AAAAADejtr8AAABAuQByvwAAAIBAfbM/AAAA
    II56rD8AAAAAuCSnPwAAAIASb54/AAAAgBVyqb8AAACA617ZvwAAAOArzLS/AAAAII7Hob8AAADg
    RB6QPwAAAKCQZp2/AAAAIGsJsb8AAACgFxizPwAAACCn5sm/AAAAgFuUp78AAADg2mWmPwAAAODr
    tLQ/AAAAoGWUiz8AAADgWniXvwAAAOBEAsg/AAAAgNeclT8AAACA64fPvwAAAIAeEbQ/AAAAoCCR
    nj8AAACgzR3OPwAAAABjLcs/AAAAoDudqD8AAADAqcmIPwAAAOBizLe/AAAAgMhgvj8AAADA3afB
    vwAAACCLmqc/AAAAAEgPxD8AAACAG6++PwAAAMDwa5U/AAAAQM8tiz8AAABgisXBvwAAAACAU+k+
    AAAAQNIgwD8AAADALVu/vwAAAIB+3Zy/AAAAAD6eqT8AAADAnCzFvwAAAMAdb6a/AAAAYBePv78A
    AADAOCTGPwAAAGBmbqE/AAAAQJwIu78AAADguBbKvwAAAOD6mME/AAAAYE4Nur8AAAAgqSGsvwAA
    AOD2LJE/AAAAICPMx78AAAAgXnLDvwAAAKD7EtO/AAAAQA8pqT8AAAAgMQjUPwAAAKDpcsE/AAAA
    oHkvyr8AAAAAKT+2PwAAAADAHHm/AAAAAOH/mz8AAAAAY1e0PwAAAKBcscc/AAAAADSEYb8AAADg
    zKOHPwAAAOCo+Ke/AAAAIA/Nlr8AAACg8ufBPwAAAICeQH6/AAAAICBTpb8AAADASOXKPwAAAMBl
    LJW/AAAAIEvGtT8AAADAXvWVPwAAAOCG8aW/AAAAYL+vp78AAACAYQGiPwAAAMCm98G/AAAAABWa
    lT8AAADgx4GrvwAAAMAqMZi/AAAA4PtXdL8AAADAZee4PwAAAECvj7u/AAAAADpuuz8AAADg4Byq
    vwAAAOAYVbI/AAAAQLRIkT8AAABA8jybPwAAAMChLrW/AAAAgODrub8AAAAgp+ewPwAAAKBvDcq/
    AAAAQEXyyT8AAAAAruLLPwAAAECV+ak/AAAAIEkvwz8AAAAgKv7CPwAAAKCtwMA/AAAAAGsNVD8A
    AABAptefPwAAAICZX9C/AAAAoNYTpL8AAABgqLfEPwAAAMDLKKe/AAAA4Ea6tz8AAADACOCTPw==
- !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - *id001
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 128
  - *id002
  - false
  - !!binary |
    AAAAwCCsrL8AAACAXwmxPwAAAIAvZLM/AAAAwLrnmL8AAACAP3+5vwAAAMDmZI8/AAAAwI5Qvb8A
    AADgZgyzvwAAAADHub0/AAAAwNzYtb8AAAAgLY/NPwAAAEBpH5G/AAAAoLGcyr8AAADgc7imvwAA
    AOD0Iqi/AAAAwOE8xD8AAAAg+bHHvwAAACCV1rG/AAAAAMGdXL8AAAAASBdlPwAAAEDFibs/AAAA
    AApApj8AAAAgfLavPwAAAAAsC4I/AAAAIHJfvL8AAABAhJjXvwAAAOCTyrq/AAAAoKhAs78AAACA
    P1qYPwAAAGDGnKO/AAAAIHDmtr8AAABg5DGbPwAAAACTjsC/AAAAwL/IlD8AAABAZkCkPwAAAADo
    Q7U/AAAAgA7Rdr8AAABgwvGwvwAAAIASlco/AAAAgBrEpT8AAACAYC/PvwAAAKCbi6Q/AAAAIGLj
    g78AAABAOF7JPwAAAICwOc4/AAAAYGtQpD8AAACAYSShPwAAACCf2cK/AAAAwCOLtj8AAADgbRrC
    vwAAAKAB9LM/AAAAQOWOyT8AAAAASnW+PwAAAACPcac/AAAAgGHwqb8AAADApoK6vwAAAGBG9Ii/
    AAAAwNuvuj8AAAAgBbG/vwAAAAALbUm/AAAAwHyutj8AAADgWba5vwAAACBfYII/AAAAoGmoqb8A
    AABA8h/GPwAAAGCIorE/AAAAwAF/w78AAACAGgjGvwAAACDpn7Y/AAAAgLFXw78AAABgWji2vwAA
    AMCDJ6k/AAAAQFQyyb8AAADgaxjLvwAAAICsR9K/AAAAgNGrqD8AAABA27DZPwAAACBzybQ/AAAA
    gGvmy78AAACgmO9xPwAAAABXKqi/AAAAIBBtoL8AAAAgTOPAPwAAAGA8Kcs/AAAAQP5ti78AAAAg
    a5+gvwAAACAr766/AAAAADR7gT8AAABA9ULNPwAAAIBGjr2/AAAAYLBdo78AAAAANGfMPwAAAECf
    nnq/AAAAoP8Cvz8AAADA3jSHPwAAAGAUVrM/AAAAIGiUiL8AAACgx2GxPwAAAADCTLK/AAAAoB4c
    nD8AAAAACACIPwAAACAt3bG/AAAAgFD3eL8AAAAAdSa6PwAAAKA8TsW/AAAAAI7xuz8AAABAXU59
    vwAAAGCLCHG/AAAAAFpZsz8AAABg8mGgvwAAAKAZ/r6/AAAAoCmevL8AAAAAps7GPwAAAIA1MMy/
    AAAAAIQhyD8AAAAARf3MPwAAAAC+2rM/AAAA4DoHwj8AAAAgtzjBPwAAAMCsFcM/AAAAwDhhmD8A
    AABAy6yZvwAAAKBOHcm/AAAAgLp4eD8AAADAjZiyPwAAAABQYVC/AAAAwJaspz8AAACAAOGHvw==
- !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - *id001
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 128
  - *id002
  - false
  - !!binary |
    AAAAgIYOtr8AAACgmOqtPwAAAMBxMJ8/AAAA4LQOib8AAAAAR1KsvwAAAGCpRXK/AAAAQHt0s78A
    AADgSMXCvwAAAEDa0bw/AAAAwGHMs78AAADg6U/NPwAAACA0Eay/AAAAIPKtx78AAABgQ5DDvwAA
    AACoiJq/AAAAwMlMyT8AAAAAVRzEvwAAAABtjsG/AAAAQPd2lb8AAADguHaYvwAAAACcd6U/AAAA
    4Pksp78AAAAgw4WkPwAAACDXzLA/AAAAAJe5vr8AAACg3EbXvwAAAOC+dbu/AAAA4AEZub8AAACA
    Hs1yPwAAAIDegZq/AAAAQGittr8AAACARg+2PwAAAMAPssW/AAAAwOo9lb8AAADAvqiOPwAAAOCc
    2bY/AAAAYCFmez8AAABAV6mzvwAAAEAXdcc/AAAAgF9GkT8AAADAfvPNvwAAAGCEFqk/AAAA4EFh
    iD8AAACAMK7KPwAAAEC6Z8s/AAAAwOoIkD8AAABAcHejPwAAAOBw/Lq/AAAAYPdSuj8AAADAOyW7
    vwAAAOCFUaY/AAAAQI7NxD8AAADg5Iy5PwAAAMAZ6YE/AAAAgHFBr78AAAAAUsvAvwAAAEDbJKG/
    AAAAwKnPwj8AAACAoQLDvwAAAAAIWm4/AAAAgMO0oj8AAADgOWHBvwAAAKALP66/AAAA4AMdub8A
    AADAXE7IPwAAAEDdfME/AAAAoP7dv78AAAAg0IrKvwAAAICu0MM/AAAA4FWDvr8AAACAjcCrvwAA
    AKCnSpo/AAAAgFoVyr8AAAAgeZjKvwAAAMBUK9S/AAAAQHylsD8AAAAAq0XUPwAAAKDRkrU/AAAA
    AILox78AAACgbyuxPwAAAEBN+q2/AAAA4NsEnD8AAADgCmK7PwAAAAAps8k/AAAA4BLAmT8AAADA
    KWCgvwAAAKApM6q/AAAAwCBwqb8AAADAL8PHPwAAAIB4wK+/AAAAIG5Zpb8AAABAaTvLPwAAAEDr
    bbG/AAAAIAWUtz8AAAAAdT6WvwAAAKAEyVa/AAAAgIEdn78AAACgQ9a3PwAAAOBUH7a/AAAAwEVA
    jj8AAAAADm9HvwAAAKAiEpm/AAAAgIagmT8AAAAg2vazPwAAAMB8d8K/AAAAoJe6qT8AAACArX6H
    PwAAAEC8ArQ/AAAA4HZCtD8AAABAQXaTvwAAAEA3tby/AAAAgARau78AAADgcdHBPwAAAEB3zdC/
    AAAAQFCIyz8AAAAgc9HKPwAAAEAiuLc/AAAAgBgwwD8AAADAE/zGPwAAACAX2bw/AAAAQGDmpj8A
    AABA9jucvwAAAKB42s+/AAAAgE4Tqj8AAABAPgTCPwAAAMC5OKO/AAAAwEIQmD8AAADA8MqWPw==
