# Generated by Django 2.2.6 on 2019-10-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='Student', max_length=32),
        ),
        migrations.AlterField(
            model_name='image',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
