# Generated by Django 2.2.6 on 2019-10-30 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20191031_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='user',
            name='Birthday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
