# Generated by Django 2.2.6 on 2019-10-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20191031_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='late',
            field=models.NullBooleanField(verbose_name='late'),
        ),
    ]
